<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>WGBTIHUC206L4O7J4.ico</ApplicationIcon>
    <ApplicationManifest></ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Remove="app.manifest" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="WGBTIHUC206L4O7J4.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="MetroFramework" Version="1.2.0.3" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.1" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.22.2" />
    <PackageReference Include="System.IO.Ports" Version="9.0.6" />
    <PackageReference Include="ZedGraph" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="DoubleBufferedPanel_Temp.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Setting.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="DoubleBufferedPanel27.cs" />
    <Compile Update="DoubleBufferedPanelCloud27.cs" />
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>